version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    network_mode: host
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    network_mode: host
    command: npm start
    depends_on:
      - postgres

  camera_feed:
    build:
      context: ./camera_feed
      dockerfile: Dockerfile
    container_name: camera_feed
    restart: unless-stopped
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    env_file: .env
    network_mode: host

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    restart: unless-stopped
