version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: ../.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    network_mode: host

  backend:
    build: ../
    container_name: backend
    network_mode: host
    restart: unless-stopped
    env_file: ../.env
    command: npm start

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    network_mode: host
